# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/Keyboard_system_ila_0_1.xci
# IP: The module: 'Keyboard_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/bd_0ffa.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0ffa || ORIG_REF_NAME==bd_0ffa} -quiet] -quiet

# IP: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/bd_0ffa_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0ffa_ila_lib_0 || ORIG_REF_NAME==bd_0ffa_ila_lib_0} -quiet] -quiet

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ffa_ila_lib_0 || ORIG_REF_NAME==bd_0ffa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ffa_ila_lib_0 || ORIG_REF_NAME==bd_0ffa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/bd_0ffa_ila_lib_0_ooc.xdc

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/bd_0ffa_ooc.xdc

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/Keyboard_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Keyboard_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/Keyboard_system_ila_0_1.xci
# IP: The module: 'Keyboard_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/bd_0ffa.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0ffa || ORIG_REF_NAME==bd_0ffa} -quiet] -quiet

# IP: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/bd_0ffa_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0ffa_ila_lib_0 || ORIG_REF_NAME==bd_0ffa_ila_lib_0} -quiet] -quiet

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ffa_ila_lib_0 || ORIG_REF_NAME==bd_0ffa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0ffa_ila_lib_0 || ORIG_REF_NAME==bd_0ffa_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/ip/ip_0/bd_0ffa_ila_lib_0_ooc.xdc

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/bd_0/bd_0ffa_ooc.xdc

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/keyboard.srcs/sources_1/bd/Keyboard/ip/Keyboard_system_ila_0_1/Keyboard_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Keyboard_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
