# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/spixy/Documents/College/EE316/EE316P4/Keyboard/keyboard/Cora-Z7-10-Master.xdc

# Block Designs: bd/Keyboard/Keyboard.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Keyboard || ORIG_REF_NAME==Keyboard} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_ps2_keyboard_to_ascii_0_0/Keyboard_ps2_keyboard_to_ascii_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Keyboard_ps2_keyboard_to_ascii_0_0 || ORIG_REF_NAME==Keyboard_ps2_keyboard_to_ascii_0_0} -quiet] -quiet

# IP: bd/Keyboard/ip/Keyboard_system_ila_0_1/Keyboard_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Keyboard_system_ila_0_1 || ORIG_REF_NAME==Keyboard_system_ila_0_1} -quiet] -quiet

# XDC: bd/Keyboard/Keyboard_ooc.xdc
