@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Mar 21 02:32:17 -0400 2022
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto aec64c5702544194aaa2e36a5b1af077 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot wrapper_behav xil_defaultlib.wrapper -log elaborate.log"
call xelab  -wto aec64c5702544194aaa2e36a5b1af077 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot wrapper_behav xil_defaultlib.wrapper -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
